// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX0a5KwGr9BUJXgkJNVrcZ78cK9zm2osE',
    appId: '1:269618378618:android:8188b8b7a112318d2108c3',
    messagingSenderId: '269618378618',
    projectId: 'crudtutorial-54da8',
    storageBucket: 'crudtutorial-54da8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnoZDqUbtb3cpGhWz_FPFGwPbtqzMBl-M',
    appId: '1:269618378618:ios:ed33331fd2c671da2108c3',
    messagingSenderId: '269618378618',
    projectId: 'crudtutorial-54da8',
    storageBucket: 'crudtutorial-54da8.appspot.com',
    iosBundleId: 'com.example.firebaseSocialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnoZDqUbtb3cpGhWz_FPFGwPbtqzMBl-M',
    appId: '1:269618378618:ios:ed33331fd2c671da2108c3',
    messagingSenderId: '269618378618',
    projectId: 'crudtutorial-54da8',
    storageBucket: 'crudtutorial-54da8.appspot.com',
    iosBundleId: 'com.example.firebaseSocialMediaApp',
  );
}
